# Learn how to configure Hyprland: https://wiki.hypr.land/Configuring/

# System defaults
source = ~/.config/hypr/defaults/autostart.conf
source = ~/.config/hypr/defaults/bindings/media.conf
source = ~/.config/hypr/defaults/bindings/clipboard.conf
source = ~/.config/hypr/defaults/bindings/tiling-v2.conf
source = ~/.config/hypr/defaults/bindings/utilities.conf
source = ~/.config/hypr/defaults/envs.conf
source = ~/.config/hypr/defaults/looknfeel.conf
source = ~/.config/hypr/defaults/input.conf
source = ~/.config/hypr/defaults/windows.conf
source = ~/.config/desktop/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/envs.conf

# Toggle config flags dynamically
source = ~/.local/state/desktop/toggles/hypr/*.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, match:class qemu

# Blur layer surfaces (waybar, walker, mako notifications, etc.)
layerrule = blur on, ignore_alpha 0.1, match:namespace waybar
layerrule = blur on, ignore_alpha 0, match:namespace walker
layerrule = blur on, ignore_alpha 0.1, match:namespace notifications
layerrule = blur on, ignore_alpha 0.1, match:namespace swayosd